spring:
  datasource:
    url: jdbc:mysql://118.25.144.147:3306/tourist?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    # Controller控制跳转的页面路径
    prefix: classpath:/templates/
mybatis:
  type-aliases-package: cn.edu.nju.tourist.bean
